[[redirects]]
  from = "/collections/*"
  to = "/collections/:splat.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "."
  command = "node update-paths.js" 