[[redirects]]
  from = "/collections/*"
  to = "/collections/:splat.html"
  status = 200

# Handle cart page
[[redirects]]
  from = "/cart/cart.html"
  to = "/cart"
  status = 301

# Handle static assets first
[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/components/*"
  to = "/components/:splat"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

# Then handle HTML files
[[redirects]]
  from = "/*.html"
  to = "/:splat.html"
  status = 200

# Finally, redirect everything else to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18" 